# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: git config
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npx eslint src --ext .js,.jsx,.ts,.tsx --max-warnings=0
    - run: npm run build
    - run: npm test

    - name: tag version
      run: |
        version=$(node -e "console.log(require('./package.json').version);")
        git tag -f ${version} -m "Release ${version}"
        git push origin ${version} # push tag